using System;

class Program {
  public static void Main (string[] args) {

    
      Console.WriteLine("what is int");
      
        Console.WriteLine("1. Boolean");
        Console.WriteLine("2. Integer");
        Console.WriteLine("3. mistake");
        Console.WriteLine("4. character");

        Console.WriteLine("Enter the correct choice");

        int opt = Convert.ToInt32(Console.ReadLine());

        if (opt == 2)
        {
            Console.WriteLine("Correct");
        }
      else
      {
                Console.WriteLine("Incorrect");
        }
    
    
    Console.WriteLine("what is this program");
      
        Console.WriteLine("1. java");
        Console.WriteLine("2. python");
        Console.WriteLine("3. c++");
        Console.WriteLine("4. c#");

        Console.WriteLine("Enter the correct choice");

        int upt = Convert.ToInt32(Console.ReadLine());

        if (upt == 4)
        {
            Console.WriteLine("Correct");
        }
      else
      {
                Console.WriteLine("Incorrect");
        }

        Console.WriteLine("what is variable");
      
        Console.WriteLine("1. value that can change");
        Console.WriteLine("2. value that can't change");
        Console.WriteLine("3. value that stays");
        Console.WriteLine("4. value that will disappear ");

        Console.WriteLine("Enter the correct choice");

        int qpt = Convert.ToInt32(Console.ReadLine());

        if (qpt == 1)
        {
            Console.WriteLine("Correct");
        }
      else
      {
                Console.WriteLine("Incorrect");
        }
      Console.WriteLine("what is not a example of high level language in programing");
      
        Console.WriteLine("1. Java");
        Console.WriteLine("2. Python");
        Console.WriteLine("3. Assembly");
        Console.WriteLine("4. C#");

        Console.WriteLine("Enter the correct choice");

        int fpt = Convert.ToInt32(Console.ReadLine());

        if (fpt == 3)
        {
            Console.WriteLine("Correct");
        }
      else
      {
                Console.WriteLine("Incorrect");
        }


     Console.WriteLine("Which reference modifier is used to define reference variables?");
    
    Console.WriteLine("1. %");
        Console.WriteLine("2. &");
        Console.WriteLine("3. *");
        Console.WriteLine("4. ref");

        Console.WriteLine("Enter the correct choice");

        int zpt = Convert.ToInt32(Console.ReadLine());

        if (zpt == 4)
        {
            Console.WriteLine("Correct");
        }
      else
      {
                Console.WriteLine("Incorrect");
        }

    
  }
}
